module.exports = {
    PORT                :   process.env.PORT || 3000,
    APP_ENV             :   process.env.NODE_ENV || "development",
    MYSQL_DB_NAME       :   process.env.MYSQL_DB_NAME || "express_project_base",
    MYSQL_USERNAME      :   process.env.MYSQL_USERNAME || "root",
    MYSQL_PASSWORD      :   process.env.MYSQL_PASSWORD || "",
    MYSQL_HOST          :   process.env.MYSQL_HOST || "172.19.0.2",
    REDIS_USERNAME      :   process.env.REDIS_USERNAME || "",
    REDIS_PASSWORD      :   process.env.REDIS_PASSWORD || "",
    REDIS_PORT          :   process.env.REDIS_PORT || "6379",
    REDIS_HOST          :   process.env.REDIS_HOST || "172.19.0.4",
    EMAIL_VERIFY_EXPIRE :   process.env.EMAIL_VERIFY_EXPIRE || 3600,
    TOKEN_SECRET        :   process.env.TOKEN_SECRET || "a",
    TOKEN_EXPIRE        :   process.env.TOKEN_EXPIRE || "1d",
    MAIL_HOST           :   process.env.MAIL_HOST || "",
    MAIL_PORT           :   process.env.MAIL_PORT || "",
    MAIL_SECURE         :   process.env.MAIL_SECURE || "",
    MAIL_VERIFY_ACCOUNT :   process.env.MAIL_VERIFY_ACCOUNT || "",
    MAIL_USERNAME       :   process.env.MAIL_USERNAME || "",
    MAIL_PASSWOR        :   process.env.MAIL_PASSWOR || "",
}